[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.10.0"
itertools = "0.13.0"
anyhow = "1.0"
thiserror = "2.0"
rayon = "1.6"
nom = "7.1"
bytecount = "0.6.8"
num-traits = "0.2.19"
nalgebra = "0.34.1"
